### ISSUE TITLE
Use file_line instead shellvar

### ISSUE THREAD

**Issue by jkroepke** [echocat/puppet-nfs#60]
Hi!

first, thank for all your work. This module help me a lot on my work.

I want to ask, If it is possible to replace augeas shellvar function with stdlib's file_line. 
Currently, the augeasproviders_core and augeasproviders_shellvar modules are not very active and augeasproviders_core do not have offical puppet4 support. 

Also puppetlabs inifile module would be an option, too.

What did you think about this?

**Comment by dwerder** [comment]
To use file_line we have first to bump the stdlib version of this module. At the moment its 3.2.0. And it should at least be 4.4.0 (better 4.8.0), because of bugfixes in file_line function for older ruby and puppet. But that should be possible.

Also we need to bump supported puppet version. At the moment we "support" 2.7+ . That should be changed to 3.0 (better >3.3)

Do you want to provide a patch? If so read DEVELOP.md

**Comment by jkroepke** [comment]
Hi,

yes I can provide a patch. 

Before I start I just wanted to ask if this is intentional.

**Comment by dwerder** [comment]
Its always a good idea to have less dependencies. So go for it.

**Comment by jkroepke** [comment]
So its okay right now?

**Comment by dwerder** [comment]
Merged and closed ;-)
